### ISSUE TITLE
Cannot create custom filament profiles.

### ISSUE THREAD

**Issue by MonkeyEnterprise** [FlashForge/Orca-Flashforge#10]
### OrcaSlicer Version

1.1.1

### OS version

Windows 11

### Printer

Adventurere m5

### How to reproduce

1. Go to create filament
2. Fill in the vendor, type and serial.
3. Create Based on Current Filament
4. Select a proile.
5. The application terminates.

### Actual results

![image](https://github.com/user-attachments/assets/df898ed5-2db9-45ec-8a8e-44d579e76eb7)

![image (2)](https://github.com/user-attachments/assets/a6e7f601-6efe-4efa-ba6b-9223ef6605cd)

### Expected results

I need to create a custom profile for using non-FlashForge filaments with my printer.

### Project file & Debug log uploads

There aren't any, and this issue is not project-specific

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Lasutriv** [comment]
FYI this is no longer an issue in the nightly build [OrcaSlicer 2.3.0-dev as of 1/26/25](https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds) (Potentially even their [latest release](https://github.com/SoftFever/OrcaSlicer/releases) 2.2.0.

**Comment by MonkeyEnterprise** [comment]
@Lasutriv The fix you are meantioning is for the orca-slicer. Flashforge create its own slicer based on orca-slicer. They deployed this software togeter with their printers. 

They failed to maintain this repository with the latest releases of orca slicer. So the support for this software is not pretty good.

I swithed to orcaslicer because of the lack of support from flashforge.

**Comment by Lasutriv** [comment]
Correct, I'm just making sure you knew about it since you specify OrcaSlicer Version and not Orca-FlashForge. Many cross-post by accident.

Hope the switch wasn't bad. I saw increase in functionality when I did, granted you can't see video feed without software customization on OrcaSlicer; I just use the mobile app for that when I'm away from the office.

**Comment by steadmanc** [comment]
You can also view the camera using the IP in a web browser.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by compdad** [comment]
Still a bug and not working in 1.3.1

**Comment by steadmanc** [comment]
I can no longer add or remove filaments to a project.  For example, nozzle .4, .6 and .8 has only one filament.  I can no longer add additional ones.  .25 has 4 and cannot delete any of those.
I can no longer change the Bed Type.  It's stuck at Smooth PEI.  I have to change it for each plate.
Do you have those issues?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MonkeyEnterprise** [comment]
@steadmanc I strongly recommend using Orca Slicer instead of FlashForge’s software. FlashForge has failed to properly maintain their software and consistently neglects its responsibility to address open support tickets, often not even responding to them.

**Comment by steadmanc** [comment]
I tried to get it to work before.  Will that software still perform the leveling, etc?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Lasutriv** [comment]
@steadmanc it can do everything and more. It just doesnt work with the devices tab out of the box. However, the Flash Maker app will or the LAN IP of your printer.

**Comment by steadmanc** [comment]
I updated to the newest version and found Orca Slicer 2.2.0 has the exact same issue as Orca-Flashforge.  Cannot change the bed type.  Cannot add or remove filaments.  I did not have these issues before this latest update of the Oraca-Flashforge software.  This tells me Flashforge did implement the last change Orca Slicer did, even the bugs.  If this isn’t a bug, what’s the fix?

Note:  I even uninstalled both products and reinstalled from scratch.  Tried with and without admin privs.

**Comment by Lasutriv** [comment]
@steadmanc as previously mentioned in this thread, the issue is fixed in the _nightly build_, 2.3.0. See [https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds](https://github.com/SoftFever/OrcaSlicer/releases/tag/nightly-builds).

**Comment by steadmanc** [comment]
The problem is still there.  Cannot change Bed type nor add or remove filaments.  If the devs have CMed their code, perhaps they should back it out to the version where those things were working and restart the dev cycle to find where the new code caused these issues.  It is honestly more broken than before.  BTW, I do appreciate the effort to maintain the software.  I’ve been a dev for 40 years.
